# Generated by Django 5.2.4 on 2025-07-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="score",
            old_name="point",
            new_name="points",
        ),
    ]
